### ISSUE TITLE
Config missing

### ISSUE THREAD

**Issue by fss012** [shzshi/TestEnvironmentBooking#1]
Hi Shashikant,

Sorry for raising this as an issue, but I couldn't find a better way to reach out to you.

I'm looking for an Environment Booking tool and came across your TestEnvironmentBooking app (which is very nice btw) and decided to give it a try and install it to see whether it would fill the requisites my colleagues have asked.

I've got it running but when I try to create a new user, or click on "forget password" for example, it gives me Not found error, (can't find /register, /main, etc.) Following your instructions wasn't enough for me to get it running correctly, due to my lack of expertise in development.

Any help would be much appreciated.

Thanks,
Fernando

**Comment by shzshi** [comment]
Hi Fernando, 

I am glad you are planning to use this environment booking tool app, will be happy to help. 

I think it something to do with .htaccess file, you need to setup the path properly. If you can send me the .htaccess file I will be able to help you.  

Cheers,
Shashi

**Comment by fss012** [comment]
Hi Shashi,

Thanks for getting back to me. I actually fixed the issue. I forgot to change my httpd.conf to enable .htaccess (AllowOverride All).

Now it is all up and running fine.

Thanks,
Fernando

**Comment by shzshi** [comment]
great thank you
