### ISSUE TITLE
Enhancement: Modify booked calendar event

### ISSUE THREAD

**Issue by ramstv** [shzshi/TestEnvironmentBooking#2]
I tried your Demo, it is pretty interesting. However, I was wondering if modify option is still in progress or is it something which can be enabled by some property.

The reason I'm asking is, in case of environment extension, I need to modify the end date.

http://www.indiadevops.com/environmentbooking/schedule

Let me know if this can be achieved.

thanks,
Ram

**Comment by shzshi** [comment]
Hi Ram, 

Thank you, modification of schedule is already in place.
Approval->Action->Sign in the column

Cheers,
Shashi

**Comment by ramstv** [comment]
Great. Thanks Shashi.
